FORMAT: 1A

# Contacts

## GET /users/{user_id}/contacts

+ Response 200 (application/json)

        [
          {
            "id": "JhehvoW6",
            "label": "random label",
            "address": "crichardson@pixope.com",
            "_links": {
              "self": {
                "href": "/users/AgKV9xeo/contacts/JhehvoW6"
              },
              "user": {
                "href": "/users/AgKV9xeo"
              }
            }
          }
        ]
        
## DELETE /users/:user_id/contacts/:id

+ Request

    + Headers
    
            Authorization: token [Authorization Token]

+ Response 204 ()
    