require "spec_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we"re
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Web::ContactsController do
  sign_in :user
  
  let(:user) { mock_model("User") }

  before do
    allow(User).to receive(:find_by).and_return(user)
    allow(user).to receive(:contacts).and_return(Contact)
  end

  describe "create" do
    include_examples "create_success", user_id: 1
    include_examples "create_failure", user_id: 1
  end

  describe "update" do
    include_examples "update_success", user_id: 1
    include_examples "update_failure", user_id: 1
  end

  describe "destroy" do
    include_examples "destroy_success", user_id: 1
    include_examples "destroy_failure", user_id: 1
  end
end
