module Revily
  module Event
    # The payload object generated by the handler that gets sent to the job via #handle
    class Payload
      include Revily::Model

      attribute :event,  type: String
      attribute :source, type: Object
      attribute :actor,  type: Object
      
      validates :event, :source, presence: true
      
      def to_hash
        active_model_serializer.new(self).serialize_object
      end

      def to_json(options={})
        to_hash.to_json(options)
      end
    end
  end
end
