Ember.EasyForm.Config.registerWrapper 'default',
  formClass: 'form-horizontal'
  fieldErrorClass: 'error'
  errorClass: 'help-inline'
  hintClass: 'help-block'
  labelClass: 'control-label'
  inputClass: 'control-group'
  wrapControls: true
  controlsWrapperClass: 'controls'
