#!/usr/bin/env bash
# set -e
if [ "$1" = "-v" ]; then
  exec 3>&1
else
  exec 3>/dev/null
fi

banner()  { echo "-----> $*" ; }
info()    { echo "       $*" ; }
warn()    { echo ">>>>>> $*" >&2 ; }

banner "Running bundler"
export PATH=".bin:$PATH"
rm -rf .bundle
bundle install --binstubs .bin --path vendor/bundle "$@"

banner "Setting up database"

info "Installing hstore extension"
{ psql -tAl -d template1 -c '\dx' | grep -E "^hstore\|" >/dev/null || \
  psql -d template1 -c 'CREATE EXTENSION IF NOT EXISTS hstore'
} >&3 2>&1

info "Creating database user"
createuser -s reveille 2>&1 >> /dev/null || "psql user already created"

info "Creating databases"
rake db:create:all

info "Running migrations"
rake db:migrate

info "Preparing test database"
rake db:test:prepare

info "Done!"
