#!/usr/bin/env bash
# set -e

. `dirname $0`/_common

function bundle_install() {
  local bundler_args="--binstubs .bin --path vendor/bundle"
  local ci_bundler_args="--without local development staging production"

  banner "Running bundler"
  export PATH=".bin:$PATH"
  rm -rf .bundle

  if [ $CI ]; then
    ./script/wad >&3 2>&1
  else
    bundle install $bundler_args "$@" >&3 2>&1
  fi
}

function install_hstore() {
  banner "Installing hstore extension"
  { psql -tAl -d template1 -c '\dx' | grep -E "^hstore\|" >/dev/null || \
    psql -d template1 -c 'CREATE EXTENSION IF NOT EXISTS hstore'
  } >&3 2>&1
}

function create_database_user() {
  local user=$1
  banner "Creating database user ${user}"
  createuser -s $user >&3 2>&1 #|| return
}

function create_databases() {
  banner "Creating databases"
  bundle exec rake db:create:all >&3 2>&1

}

function run_migrations() {
  banner "Running migrations"
  bundle exec rake db:migrate >&3 2>&1
}

function prepare_test_database() {
  banner "Preparing test database"
  # createdb revily_test >&3 2>&1
  # bundle exec rake db:migrate RAILS_ENV=test
  bundle exec rake db:test:prepare >&3 2>&1
}

function install_bower() {
  banner "Installing bower"
  npm install bower >&3 2>&1
}

bundle_install
install_hstore
create_database_user 'revily'
create_databases
run_migrations
prepare_test_database
install_bower
finalize
