#= require ./application_adapter
#= require_tree ./lib
#= require_tree ./mixins
#= require_tree ./models
#= require ./controllers/controller
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./helpers
#= require_tree ./components
#= require_tree ./templates
#= require ./routes/route
#= require_tree ./routes
#= require ./router
#= require_self
