module Reveille
  module Event
    # The payload object generated by the handler that gets sent to the job via #handle
    class Payload
      
      attr_accessor :event, :source

      def initialize(event, source)
        @event = event
        @source = source
      end

    end
  end
end